### PR TITLE
Json equals

### LINKED ISSUE #184: json_test fail in g++ 6.2.0 environment
We should fix tests that assume the hash key ordering.

```
$ ./waf --checkone=json_test
Waf: Entering directory `/home/eiichiro/git/pficommon/build'
[70/78] utest: build/src/text/json_test
Waf: Leaving directory `/home/eiichiro/git/pficommon/build'
test summary
  tests that pass 0/1
  tests that fail 1/1
    /home/eiichiro/git/pficommon/build/src/text/json_test
Running main() from gtest_main.cc
[==========] Running 27 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 27 tests from json
[ RUN      ] json.to_json
../src/text/json_test.cpp:240: Failure
Value of: oss.str()
  Actual: "{\"hoge\":3.14,\"abc\":1.23}"
Expected: "{\"abc\":1.23,\"hoge\":3.14}"
Which is: "{"abc":1.23,"hoge":3.14}"
[  FAILED  ] json.to_json (1 ms)
[ RUN      ] json.from_json
[       OK ] json.from_json (0 ms)
[ RUN      ] json.merge
[       OK ] json.merge (0 ms)
[ RUN      ] json.merge_with
[       OK ] json.merge_with (0 ms)
[ RUN      ] json.size
[       OK ] json.size (0 ms)
[ RUN      ] json.type
[       OK ] json.type (0 ms)
[ RUN      ] json.is
[       OK ] json.is (0 ms)
[ RUN      ] json.parse
[       OK ] json.parse (0 ms)
[ RUN      ] json.bignum_parse
[       OK ] json.bignum_parse (0 ms)
[ RUN      ] json.pretty
[       OK ] json.pretty (0 ms)
[ RUN      ] json.clone
[       OK ] json.clone (0 ms)
[ RUN      ] json.utf8
[       OK ] json.utf8 (0 ms)
[ RUN      ] json.utf8_2
[       OK ] json.utf8_2 (0 ms)
[ RUN      ] json.utf8_without_escaping
[       OK ] json.utf8_without_escaping (0 ms)
[ RUN      ] json.with_default
[       OK ] json.with_default (0 ms)
[ RUN      ] json.optional
../src/text/json_test.cpp:1016: Failure
Value of: "{\"abc\":123,\"def\":null}"
  Actual: "{"abc":123,"def":null}"
Expected: oss.str()
Which is: "{\"def\":null,\"abc\":123}"
../src/text/json_test.cpp:1023: Failure
Value of: "{\"abc\":123,\"def\":456}"
  Actual: "{"abc":123,"def":456}"
Expected: oss.str()
Which is: "{\"def\":456,\"abc\":123}"
[  FAILED  ] json.optional (0 ms)
[ RUN      ] json.cast_to_json
[       OK ] json.cast_to_json (0 ms)
[ RUN      ] json.serialization
[       OK ] json.serialization (1 ms)
[ RUN      ] json.out_of_range
[       OK ] json.out_of_range (0 ms)
[ RUN      ] json.parse_multiple_jsons
[       OK ] json.parse_multiple_jsons (0 ms)
[ RUN      ] json.parse_invalid_multiple_json
[       OK ] json.parse_invalid_multiple_json (0 ms)
[ RUN      ] json.escape_ctrl
[       OK ] json.escape_ctrl (0 ms)
[ RUN      ] json.invalid_json_num
[       OK ] json.invalid_json_num (0 ms)
[ RUN      ] json.finite
[       OK ] json.finite (0 ms)
[ RUN      ] json.named_optional_value
[       OK ] json.named_optional_value (0 ms)
[ RUN      ] json.named_optional_value_null
[       OK ] json.named_optional_value_null (0 ms)
[ RUN      ] json.not_found_member
[       OK ] json.not_found_member (0 ms)
[----------] 27 tests from json (2 ms total)

[----------] Global test environment tear-down
[==========] 27 tests from 1 test case ran. (2 ms total)
[  PASSED  ] 25 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] json.to_json
[  FAILED  ] json.optional

 2 FAILED TESTS

test failed
```

### PR DESCRIPTION
**Pull request by takei-yuya**
fixes #184

### CODE REVIEW

File: src/text/json/base.h [hunk 1]
```diff
@@ -801,6 +801,62 @@ inline std::ostream& operator<<(std::ostream& os, const without_escape_tag<T>& j
...
+    }
+    if (lhs.type() == json::Float && rhs.type() == json::Integer) {
+      return dynamic_cast<json_float *>(lhs.get())->get() == dynamic_cast<json_integer *>(rhs.get())->get();
+    }
+  }
+  if (lhs.type() != rhs.type()) return false;
+
+  switch (lhs.type()) {
+   case json::Null:
+     return true;
```
Comment (takei-yuya) [inline src/text/json/base.h]: 🤔

Comment (takei-yuya) [reply src/text/json/base.h]: I think it's ok

**Comment by himkt** [comment]
LGTM!
